### ISSUE TITLE
Duplicate saved themes

### ISSUE THREAD

**Issue by gargshruti30** [mozilla/Themer#170] opened 2018-03-14 14:27 UTC
1.Go to https://mozilla.github.io/Themer/
2.On clicking the Save button again and again, duplicate themes are saved.

But according to me saving duplicate themes should not be allowed.

![screenshot from 2018-03-14 19-52-16](https://user-images.githubusercontent.com/34654829/37408027-42e6fc52-27c1-11e8-9d53-4830658f6e1c.png)

**Comment by chuckharmston** [comment] 2018-03-14 14:28
I'll be closing this as a duplicate of #166, but thanks so much for filing.

**Closed by chuckharmston** 2018-03-14 14:28 UTC

**Comment by gargshruti30** [comment] 2018-03-14 14:30
Hey. I am Shruti, a first year student studying in Netaji Subhas Institute
of Technology,Dwarka India pursuing Bachelor of Engineering in Information
Technology.
I am a first time aspirant of Outreachy and I am interested in working in
this project.

I was able to run the project on localhost:8080 and I could see bugs in UI
and responsiveness of the site, so should I work upon it ?

Also can you please tell me some beginner level issues so that i could work
upon them.
Hope to see an early reply.
Thank you.

**Comment by meandavejustice** [comment] 2018-03-17 12:46
Hey @gargshruti30 the `good-first-issue` labels are a good place to start https://github.com/mozilla/Themer/labels/good%20first%20issue. More issues will be added to this tag when we do triages (usually weekly). Another good place to look for general good first bugs on all active test pilot experiments is https://contribute.testpilot.firefox.com/

Cheers! thanks for the interest in contributing. :)

**Comment by gargshruti30** [comment] 2018-03-17 12:50
@meandavejustice Thanks for the help. I will look for good-first-issue labels.
