### ISSUE TITLE
A tooltip is wrongly displayed when the "Color Picker" background is hovered

### ISSUE THREAD

**Issue by Softvision-MariusComan** [mozilla/Themer#192] opened 2018-03-21 16:05 UTC
**[Affected versions]:**
- Firefox 59.0.1 and up

**[Affected Platforms]:**
- All Windows
- All Mac
- All Linux

**[Prerequisites]:**
- Have a Firefox profile with the latest version of the "Themer" add-on (0.0.32 custom build from 2018-03-21) installed.

**[Steps to reproduce]:**
1. Open the browser with the profile from prerequisites.
2. Click the "Toolbar Icons and Text" bubble text. 
3. Hover the "Color Picker" background.
4. Observe the behavior.

**[Expected result]:**
- No tooltip is displayed.

**[Actual result]:**
- The "Toolbar Icons and Text" tooltip is displayed.

**[Notes]:**
- The issue is reproducible for all the color pickers.
- Attached a screen recording of the issue: 
![rec of the issue](https://user-images.githubusercontent.com/31243259/37721502-5d3592b4-2d32-11e8-8053-18e127de3fcb.gif)

**Comment by shr7** [comment] 2018-03-21 22:10
I'd like to take this up.

**Comment by lmorchard** [comment] 2018-03-22 18:54
This basically looks like a duplicate of #189.

**Closed by lmorchard** 2018-03-22 18:54 UTC
